### ISSUE TITLE
Feature request: no blank space when avatar is not provided

### ISSUE THREAD

**Issue by adrcotfas** [TheAndroidMaster/Attribouter#42]
I hope I don't spam you too much with these requests :).

**Comment by TheAndroidMaster** [comment]
I have mixed feelings on this one. I don't want to make the default behavior to remove the space since the text will no longer be aligned if one person has an avatar and another does not - I would prefer to have it display a generic avatar drawable instead to make it more consistent. 

To change this behavior, you could override the layout file and make the imageview invisible, but this would mean that no avatars are displayed at all, which doesn't really solve your problem.

**Comment by TheAndroidMaster** [comment]
Well, when #37 is fixed this will no longer be a problem since you'll simply be able to extend `ContributorsItemData` to change this behavior on your own.

Yay, first `wontfix` label in the repo! Idk if that's a good thing or not but it exists.

**Comment by TheAndroidMaster** [comment]
Do people normally leave `wontfix` issues open or closed? I have no idea what to do in this situation.

**Comment by TheAndroidMaster** [comment]
Do people normally leave `wontfix` issues open or closed? I have no idea what to do in this situation.

**Comment by adrcotfas** [comment]
I think it should be closed :+1:
